function [] = create_csv(features)
    Table = array2table(features, ...
        'VariableNames', ...
        {
            'HRV', 'SDSD', 'SDNN', 'RMSSD', 'PNN50', 'TINN', 'HTI', ...
            'APEN', 'SD1', 'SD2', 'SDRatio' ...
            'PLF', 'PHF', 'LFHFRatio', 'VLF','LF', 'HF' ...,
            'e1', 'e2', 'e3', 'e4', 'e5', 'e6', 'e7', 'e8', 'e9', 'e10' ...
            'e11', 'e12', 'k1', 'k2', 'k3', 'k4', 'k5', 'k6', 'k7', 'k8' ...
            'k9', 'k10', 'k11', 'k12'
        } ...
    );
    writetable(Table, 'C:\Users\SaiGanesh\Desktop\ECG project\test3.xlsx');
end
